name: Deployment pipeline

env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}
  COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), ', ') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:ui
      - name: test frontend
        run: npm run test:client
      - name: test backend
        run: |
          npm run start:test &
          npx wait-on http://localhost:3003
          npm run test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }}
        run: |
          echo "$COMMIT_MESSAGES"
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
